--게임 유저 정보 테이블
CREATE TABLE USERINFO (
IDX NUMBER(5) PRIMARY KEY,
ID VARCHAR2(20) NOT NULL,
PWD VARCHAR2(30) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
EMAIL VARCHAR2(30) NOT NULL,
TEL VARCHAR2(20) NOT NULL,
RANK NUMBER(10),
SCORE NUMBER(10),
INDATE DATE NOT NULL,
ADMIN NUMBER(1) NOT NULL
);

-- 테이블 작동 확인
SELECT * FROM USERINFO;

-- ADMIN 계정
INSERT INTO USERINFO
VALUES(USERINFO_SEQ.NEXTVAL, 'admin', 'admin', '관리자', 'admin@team2.com', '010-0000-0000', 0, 0, SYSDATE, 1);

COMMIT;

--테이블 PRIMARY KEY 증가 시퀸스
CREATE SEQUENCE USERINFO_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;
--점수 증가 시퀸스
CREATE SEQUENCE USERSCORE_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

/*시퀀스 초기화(ex 계정 삭제시 빈공간)
ALTER SEQUENCE USERINFO_SEQ INCREMENT BY 1; -- INCREMENT 값 수정 하고 다시 1로 수정
SELECT USERINFO_SEQ.NEXTVAL FROM DUAL;*/

/* 시퀸스, 테이블 삭제
DROP SEQUENCE USERINFO_SEQ;
DROP TABLE USERINFO;
*/

-- 점수는 게임 한판 할때마다 + 1 점수는 랭킹에 반영

